'use client';

import { useEffect, useState } from 'react';
import { useParams } from 'next/navigation';
import Link from 'next/link';
import { ArrowLeft, Brain } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { QuizEngine } from '@/components/quiz/quiz-engine';
import { ChapterCompletionBanner } from '@/components/textbook/chapter-completion-banner';
import { getChapterBySlug, nextChapter } from '@/data/textbook';
import { getStaticTextbookQuiz } from '@/data/textbook/quizzes';
import { useAuth } from '@/hooks/use-auth';
import { recordChapterQuizPass } from '@/app/actions/textbook';
import type { QuizAttempt } from '@/types';

export default function ChapterQuizPage() {
  const params = useParams();
  const slug = params?.slug as string;
  const chapter = getChapterBySlug(slug);
  const quiz = chapter ? getStaticTextbookQuiz(chapter.slug) : null;

  const { user } = useAuth();
  const [passed, setPassed] = useState(false);

  async function handleComplete(attempt: QuizAttempt) {
    if (!attempt.passed || !user || !chapter) return;
    // Records the chapter pass toward the textbook MILESTONE certificate.
    // The chapter-quiz badge/report is generated by QuizEngine's evidence panel.
    setPassed(true);
    await recordChapterQuizPass({ userId: user.uid, slug: chapter.slug });
  }

  if (!chapter) {
    return (
      <div className="container mx-auto py-16 px-4 max-w-2xl">
        <Card>
          <CardContent className="p-8 text-center space-y-4">
            <h1 className="font-headline text-2xl font-semibold">Chapter not found</h1>
            <Button asChild>
              <Link href="/textbook">
                <ArrowLeft className="h-4 w-4 mr-2" /> Back to Textbook
              </Link>
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  if (!quiz) {
    return (
      <div className="container mx-auto py-16 px-4 max-w-2xl">
        <Card>
          <CardContent className="p-8 text-center space-y-4">
            <h1 className="font-headline text-2xl font-semibold">
              Quiz not yet available
            </h1>
            <Button asChild>
              <Link href={`/textbook/chapters/${chapter.slug}`}>
                <ArrowLeft className="h-4 w-4 mr-2" /> Back to Chapter
              </Link>
            </Button>
          </CardContent>
        </Card>
      </div>
    );
  }

  return (
    <div className="container mx-auto py-6 md:py-10 px-4 max-w-3xl space-y-6">
      <div>
        <Link
          href={`/textbook/chapters/${chapter.slug}`}
          className="inline-flex items-center gap-1.5 text-sm text-muted-foreground hover:text-primary mb-2"
        >
          <ArrowLeft className="h-3 w-3" /> Back to Chapter {chapter.number}
        </Link>
        <h1 className="font-headline text-2xl md:text-3xl font-bold flex items-center gap-2">
          <Brain className="h-6 w-6 text-primary" /> Knowledge Check
        </h1>
        <p className="text-muted-foreground mt-1">
          {quiz.questions.length} questions · pass at {quiz.passingScorePercent}% to
          complete this chapter and progress toward your Master Certificate.
        </p>
      </div>

      {passed && (
        <ChapterCompletionBanner
          chapter={chapter}
          next={nextChapter(chapter.slug)}
        />
      )}

      <QuizEngine quiz={quiz} onComplete={handleComplete} />
    </div>
  );
}
