/* AUTO-GENERATED by src/scripts/import-textbook.ts — do not edit by hand. */
import type { Chapter, BookMeta } from '@/types/textbook';

import ch1 from './chapters/01-architecture-of-moral-reasoning';
import ch2 from './chapters/02-ethical-relativism';
import ch3 from './chapters/03-divine-command-and-euthyphro';
import ch4 from './chapters/04-social-media-and-ethical-egoism';
import ch5 from './chapters/05-utilitarianism-and-warfare';
import ch6 from './chapters/06-animals-and-technology';
import ch7 from './chapters/07-kantianism-utopias-dystopias';
import ch8 from './chapters/08-virtue-ethics-and-technology';
import ch9 from './chapters/09-surveillance-privacy-social-contract';
import ch10 from './chapters/10-bioengineering-enhancement-justice';
import ch11 from './chapters/11-virtual-reality-and-personhood';
import ch12 from './chapters/12-ai-care-ethics';

export const chapters: Chapter[] = [ch1, ch2, ch3, ch4, ch5, ch6, ch7, ch8, ch9, ch10, ch11, ch12];

export const bookMeta: BookMeta = {
  title: 'The Ethics of Technology Through Science Fiction',
  subtitle: 'Rehearsing tomorrow\'s moral decisions in the space sci-fi opened up for us.',
  author: 'Dr. Blaine Fisher',
  copyright: 'Copyright © 2025 by Blaine Fisher',
  totalChapters: 12,
  totalWordCount: 83540,
  estimatedReadingHours: 6.4,
  heroImage: '/textbook/hero.svg',
  overview: `A twelve-chapter course that reads technology's hardest ethical questions through the science fiction stories that have been rehearsing them for two centuries. Each chapter pairs a plain-language essay on an ethical tradition with an original short story that puts the ideas under pressure, followed by a Knowledge Check, reflection prompts, and practical takeaways for builders and policymakers.`,
  learnerOutcomes: [
    'Name and apply the major ethical traditions to live technology decisions.',
    'Read science fiction as a rehearsal space for real-world ethical dilemmas.',
    'Diagnose where systems fail — at the levels of rules, outcomes, character, and power.',
    'Write, design, and govern technology with sharper moral vocabulary and better instincts.',
  ],
};

export function getChapterBySlug(slug: string): Chapter | undefined {
  return chapters.find((c) => c.slug === slug);
}

export function getChapterByNumber(n: number): Chapter | undefined {
  return chapters.find((c) => c.number === n);
}

export function nextChapter(slug: string): Chapter | undefined {
  const idx = chapters.findIndex((c) => c.slug === slug);
  return idx >= 0 && idx < chapters.length - 1 ? chapters[idx + 1] : undefined;
}

export function prevChapter(slug: string): Chapter | undefined {
  const idx = chapters.findIndex((c) => c.slug === slug);
  return idx > 0 ? chapters[idx - 1] : undefined;
}
