/**
 * generate-textbook-images.ts
 *
 * Regenerates the textbook hero and chapter header images as raster
 * artwork using Google's Imagen via Genkit. Outputs to public/textbook/
 * as .webp files (replacing the SVG fallbacks generated by
 * generate-textbook-svgs.ts).
 *
 * Requires:
 *   - GOOGLE_GENAI_API_KEY (or GOOGLE_API_KEY) in process.env
 *   - The existing @genkit-ai/googleai dependency (already installed)
 *
 * Usage:
 *   GOOGLE_GENAI_API_KEY=... npx tsx src/scripts/generate-textbook-images.ts
 *
 * If the API key is missing or any image fails to generate, the script
 * exits with a non-zero status without overwriting existing files. The
 * SVG fallbacks remain available, so the site never ships without
 * imagery.
 */

import { promises as fs } from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);
const REPO_ROOT = path.resolve(__dirname, '..', '..');
const OUT_DIR = path.join(REPO_ROOT, 'public', 'textbook');

const STYLE_PREFIX =
  'editorial science-fiction illustration, dark navy background, cyan and magenta neon accents, painterly brush strokes, philosophical and contemplative mood, no text, no logos, 16:9 cinematic aspect ratio, high detail';

const PROMPTS: Array<{ slug: string; prompt: string }> = [
  {
    slug: 'hero',
    prompt:
      'a vast holographic library of interconnected stories rising into a starfield, ethical pathways branching like neon constellations, philosophical and inviting',
  },
  {
    slug: 'chapter-01',
    prompt:
      'a luminous architectural lattice of moral frameworks orbiting a starship medical bay, three pillars of light representing rules, outcomes, and character',
  },
  {
    slug: 'chapter-02',
    prompt:
      'a translucent globe stitched together from many cultures, ethical lines crossing borders, a single algorithm being deployed across all of them',
  },
  {
    slug: 'chapter-03',
    prompt:
      'a cathedral of code with stone arches dissolving into pixels, an ancient stone tablet beside a glowing interface, the Euthyphro question carved as glyphs',
  },
  {
    slug: 'chapter-04',
    prompt:
      'an attention economy as a dense crowd of figures looking at glowing rectangles, a single optimizer drone above tuning their rewards, intimacy turned to performance',
  },
  {
    slug: 'chapter-05',
    prompt:
      'an austere bureau weighing lives on a brass scale, autonomous combat drones suspended above, the calculus visible as floating numerical glyphs',
  },
  {
    slug: 'chapter-06',
    prompt:
      'an engineered mars ranch with cybernetic livestock, ethical horizons stretching past the dome, the moral circle widening across species',
  },
  {
    slug: 'chapter-07',
    prompt:
      'a Kantian cathedral made of categorical imperatives, persons as ends rendered as glowing figures, a utopia and dystopia mirrored across a clear pane',
  },
  {
    slug: 'chapter-08',
    prompt:
      'a slow garden of olive trees and circuit-vines, a wise figure tending both, virtue cultivated under shifting light',
  },
  {
    slug: 'chapter-09',
    prompt:
      'a city of glass towers webbed with sensor lines, a person reading a fifty-page contract by neon, eyes everywhere watching gently',
  },
  {
    slug: 'chapter-10',
    prompt:
      'a double helix split in two, one strand engineered with diamond glyphs, a sleeve-like genetic identity card glowing on the table',
  },
  {
    slug: 'chapter-11',
    prompt:
      'a person stepping into an experience-machine portal, a second self watching from outside, the boundary of reality wavering like a soap bubble',
  },
  {
    slug: 'chapter-12',
    prompt:
      'a quiet hospital room at dawn with a humanoid AI caregiver gently holding a hand, neural threads connecting to a constellation overhead',
  },
];

async function generate(): Promise<void> {
  const apiKey = process.env.GOOGLE_GENAI_API_KEY || process.env.GOOGLE_API_KEY;
  if (!apiKey) {
    console.error(
      '[textbook-images] No GOOGLE_GENAI_API_KEY set. Aborting without overwriting SVG fallbacks.'
    );
    process.exit(2);
  }

  // Lazy-load genkit so the script can be parsed even when @genkit-ai is
  // not installed.
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let genkit: any;
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  let googleAI: any;
  try {
    genkit = await import('genkit');
    googleAI = await import('@genkit-ai/googleai');
  } catch (err) {
    console.error('[textbook-images] Could not import Genkit modules:', err);
    process.exit(2);
  }

  const ai = genkit.genkit({
    plugins: [googleAI.googleAI({ apiKey })],
    model: googleAI.googleAI.model('imagen-3.0-generate-001'),
  });

  await fs.mkdir(OUT_DIR, { recursive: true });

  for (const { slug, prompt } of PROMPTS) {
    const file = path.join(OUT_DIR, `${slug}.webp`);
    console.log(`[textbook-images] Generating ${slug} …`);
    try {
      const { media } = await ai.generate({
        prompt: `${prompt}. ${STYLE_PREFIX}`,
        config: { numberOfImages: 1 },
      });
      const url: string | undefined = media?.url;
      if (!url) {
        console.warn(`[textbook-images]   no image returned for ${slug}, skipping`);
        continue;
      }
      // Imagen returns a data URL; decode and write
      const m = url.match(/^data:.*;base64,(.*)$/);
      const buffer = m
        ? Buffer.from(m[1], 'base64')
        : Buffer.from(await (await fetch(url)).arrayBuffer());
      await fs.writeFile(file, buffer);
      console.log(`[textbook-images]   wrote ${file}`);
    } catch (err) {
      console.error(`[textbook-images] Failed for ${slug}:`, err);
    }
  }

  console.log(`\n[textbook-images] Done.`);
  console.log(
    'Note: chapter Chapter.heroImage paths point to .svg by default (the deterministic fallback).\n' +
      'After confirming the .webp images look right, update chapter data files to reference .webp,\n' +
      'or extend the import script to emit .webp paths.'
  );
}

generate().catch((err) => {
  console.error(err);
  process.exit(1);
});
